Currency converter
BorisZelikman/my-money pull request #31
Opened 2023-09-16 21:00 UTC by nudefingers

2023-09-17 10:23 UTC, SokolovAl requested changes

2023-09-17 10:23 UTC, SokolovAl commented on src/components/Items/CurrencyConverter.js
> +import React, { useState, useEffect } from "react";
убери лишний импорт React

2023-09-17 10:23 UTC, SokolovAl commented on src/components/Items/CurrencyConverter.js
> +  ////
для чего нужны ////?

2023-09-17 10:23 UTC, SokolovAl commented on src/components/Items/CurrencyConverter.js
> +    console.log(currencies);
если это нужно было для отладки, то в продакшен нужно убрать или заменить на модальное окно

2023-09-17 10:23 UTC, SokolovAl commented on src/components/Items/CurrencyConverter.js
>        console.error(error.message)
если это нужно было для отладки, то в продакшен нужно убрать или заменить на модальное окно

2023-09-17 19:28 UTC, nudefingers commented on src/components/Items/CurrencyConverter.js
> +import React, { useState, useEffect } from "react";
убрала

2023-09-17 19:28 UTC, nudefingers commented on src/components/Items/CurrencyConverter.js
> +  ////
убрала

2023-09-17 19:33 UTC, nudefingers commented on src/components/Items/CurrencyConverter.js
> +    console.log(currencies);
убрала

2023-09-18 11:26 UTC, SokolovAl approved these changes

2023-09-18 11:27 UTC, merged