Nav bar
BorisZelikman/my-money pull request #7
Opened 2023-09-11 12:26 UTC by LDubersht

Navigation Bar without integration

2023-09-11 12:46 UTC, SokolovAl requested changes
То, что нужно 100% - переписать NavigationBar используя materialUI.
Не понятно, ты в итоге решил использовать context или отказался от него?

2023-09-11 12:46 UTC, SokolovAl commented on src/App.js
> +                        <Route path = "/" element = {<Auth setUser = {setUser}/>}></Route>
Откуда появился setUser и для чего?

2023-09-11 12:46 UTC, SokolovAl commented on src/App.js
> +                        <Route path = "/user-profile/:userId/operationhistory" element = {<OperationHistory/>}/>
Сделай эндпоинт более читабельным. Например через "-", "_" или используй camelCase

2023-09-11 12:46 UTC, SokolovAl commented on src/components/Items/NavigationBar.js
> +  return (
Почему не использовал mateial UI?

2023-09-11 12:46 UTC, SokolovAl commented on src/routes/Auth.js
> +export const Auth = ({ setUser }) => {
Для чего переписал метод?

2023-09-11 12:46 UTC, SokolovAl commented on src/routes/Registration.js
> +export const Registration = ({ setUser }) => {
Для чего переписал метод?

2023-09-11 12:46 UTC, SokolovAl commented on src/App.js
> +            <UserProvider>
Если не используешь context, зачем UserProvider?

2023-09-11 12:46 UTC, SokolovAl commented on src/data/UserContext.js
> +import React, { createContext, useState } from 'react';
Для чего это нужно, если ты сказал, что не используешь context?

2023-09-11 14:20 UTC, LDubersht commented on src/App.js
> +                        <Route path = "/" element = {<Auth setUser = {setUser}/>}></Route>
Для хранения userID в  App.js. Он в App.js нужен для отработки роутинга  в навбаре (возможно понадобиться в роутинге, но не факт).

2023-09-11 14:25 UTC, LDubersht commented on src/App.js
> +                        <Route path = "/user-profile/:userId/operationhistory" element = {<OperationHistory/>}/>
Done for "operationhistory"
Просьба в следующий раз указывать номер строки или предмет работ. Тут 4 эндпоинта

2023-09-11 14:28 UTC, LDubersht commented on src/routes/Auth.js
> +export const Auth = ({ setUser }) => {
Для хранения userID в App.js. Он в App.js нужен для отработки роутинга в навбаре (возможно понадобиться в роутинге, но не факт).
Тут передается в метод функция установки userID в App.js

2023-09-11 14:28 UTC, LDubersht commented on src/routes/Registration.js
> +export const Registration = ({ setUser }) => {
Для хранения userID в App.js. Он в App.js нужен для отработки роутинга в навбаре (возможно понадобиться в роутинге, но не факт).
Тут передается в метод функция установки userID в App.js

2023-09-11 14:29 UTC, LDubersht commented on src/App.js
> +            <UserProvider>
Потерял при вырезании контекста.

2023-09-11 14:31 UTC, LDubersht commented on src/data/UserContext.js
> +import React, { createContext, useState } from 'react';
Потерял при вырезании контекста.

2023-09-11 14:52 UTC, BorisZelikman approved these changes

2023-09-11 19:51 UTC, LDubersht commented on src/components/Items/NavigationBar.js
> +  return (
Done

2023-09-11 19:56 UTC, LDubersht commented
Material заюзал, Context вырезал, далее по комментам.

2023-09-11 20:09 UTC, SokolovAl reviewed
Исправь ситуацию с комментированным кодом

2023-09-11 20:09 UTC, SokolovAl commented on src/components/Items/NavigationBar.js
> +function NavigationBar({ userID }) {
Code style. Используем тип записи:
export const YourFunction = () => {}

2023-09-11 20:09 UTC, SokolovAl commented on src/routes/UserProfile.js
> +// import {signOut} from "firebase/auth";
Комментированный код не стоит заливать. Или удаляй или оставь как есть. Это касается всего документа

2023-09-11 20:35 UTC, SokolovAl approved these changes

2023-09-12 03:56 UTC, merged

2023-09-12 03:56 UTC, LDubersht commented
Всем спасибо